/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package cliente_tienda;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Logica.conexion;
/**
 *
 * @author German Pulgarin Alex Arias
 */
public class JF_tienda extends javax.swing.JFrame {

    String [][]data={};
    String [] cabecera={"Nombre","apellido","edad","cedula","cupo","ocupacion"};
    DefaultTableModel md;
    public JF_tienda() {
        initComponents();
        md=new DefaultTableModel(data,cabecera);
        tbl_Datos_Clientes.setModel(md);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        TXTnombre = new javax.swing.JTextField();
        TXTapellido = new javax.swing.JTextField();
        TXTedad = new javax.swing.JTextField();
        TXTcupo = new javax.swing.JTextField();
        BTNguardar = new javax.swing.JButton();
        BTNsalir = new javax.swing.JButton();
        BTNnuevo = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_Datos_Clientes = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        BTNborrarcte = new javax.swing.JButton();
        BTNborrarall = new javax.swing.JButton();
        BTNbuscar = new javax.swing.JButton();
        CBB_ocupacion = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        btnmodificar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        TXTcedula = new javax.swing.JTextField();
        jMenuBar3 = new javax.swing.JMenuBar();
        Jcliente = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        Jarticulos = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        Jfacturacion = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        Jacerca = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tienda");

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        BTNguardar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BTNguardar.setText("Guardar");
        BTNguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNguardarActionPerformed(evt);
            }
        });

        BTNsalir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BTNsalir.setText("Salir");
        BTNsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNsalirActionPerformed(evt);
            }
        });

        BTNnuevo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BTNnuevo.setText("Nuevo");
        BTNnuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNnuevoActionPerformed(evt);
            }
        });

        tbl_Datos_Clientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Apellido", "Edad", "Cedula", "Cupo", "Ocupacion"
            }
        ));
        jScrollPane2.setViewportView(tbl_Datos_Clientes);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Ocupacion:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Cupo:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Edad:");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Nombre:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Apellido:");

        BTNborrarcte.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BTNborrarcte.setText("Borrar cte");
        BTNborrarcte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNborrarcteActionPerformed(evt);
            }
        });

        BTNborrarall.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BTNborrarall.setText("Borrar todo");
        BTNborrarall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNborrarallActionPerformed(evt);
            }
        });

        BTNbuscar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BTNbuscar.setText("Buscar");
        BTNbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNbuscarActionPerformed(evt);
            }
        });

        CBB_ocupacion.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        CBB_ocupacion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Empleado", "Independiente", "Jubilado", "pensionado" }));
        CBB_ocupacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBB_ocupacionActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Tienda de Alex_German");

        btnmodificar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnmodificar.setText("Modificar");
        btnmodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmodificarActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Cedula");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(73, 73, 73)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(TXTapellido)
                                    .addComponent(TXTnombre)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(TXTedad, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 136, Short.MAX_VALUE)))
                                .addGap(49, 49, 49))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CBB_ocupacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TXTcupo, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TXTcedula, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BTNguardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BTNsalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BTNnuevo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnmodificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BTNborrarall, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BTNbuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BTNborrarcte, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(221, 221, 221)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel4)
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TXTnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTNnuevo)
                    .addComponent(jLabel1)
                    .addComponent(BTNborrarcte))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TXTapellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTNguardar)
                    .addComponent(jLabel2)
                    .addComponent(BTNborrarall))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTNsalir)
                    .addComponent(jLabel3)
                    .addComponent(BTNbuscar)
                    .addComponent(TXTedad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnmodificar)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(TXTcupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CBB_ocupacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(TXTcedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        Jcliente.setText("Cliente");

        jMenuItem1.setText("Frclientes");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        Jcliente.add(jMenuItem1);

        jMenuItem2.setText("ListClientes");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        Jcliente.add(jMenuItem2);

        jMenuBar3.add(Jcliente);

        Jarticulos.setText("Articulos");

        jMenuItem3.setText("FrArticulos");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        Jarticulos.add(jMenuItem3);

        jMenuItem4.setText("ListArticulos");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        Jarticulos.add(jMenuItem4);

        jMenuBar3.add(Jarticulos);

        Jfacturacion.setText("Facturacion");

        jMenuItem5.setText("ForFacturacion");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        Jfacturacion.add(jMenuItem5);

        jMenuItem6.setText("ListVentas");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        Jfacturacion.add(jMenuItem6);

        jMenuBar3.add(Jfacturacion);

        Jacerca.setText("Acerca De");

        jMenuItem7.setText("Conozcanos");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        Jacerca.add(jMenuItem7);

        jMenuItem8.setText("Version");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        Jacerca.add(jMenuItem8);

        jMenuBar3.add(Jacerca);

        jMenu1.setText("Salir");

        jMenuItem9.setText("Salir");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem9);

        jMenuBar3.add(jMenu1);

        setJMenuBar(jMenuBar3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTNguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNguardarActionPerformed
        // TODO add your handling code here:
        String nombre=TXTnombre.getText();
        String apellido=TXTapellido.getText();
        String edad=TXTedad.getText();
        String cedula=TXTcedula.getText();
        String cupo=TXTcupo.getText();
        String ocupacion=CBB_ocupacion.getSelectedItem().toString();
        
        conexion sql=new conexion();
        sql.InsertarCliente(cedula, nombre, apellido, edad, cupo, ocupacion);

    }//GEN-LAST:event_BTNguardarActionPerformed

    private void BTNsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNsalirActionPerformed
        // TODO add your handling code here:

        System.exit(0);
    }//GEN-LAST:event_BTNsalirActionPerformed

    private void BTNnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNnuevoActionPerformed
        // TODO add your handling code here:
        TXTnombre.setText(" ");
        TXTapellido.setText(" ");
        TXTedad.setText(" ");
        TXTcedula.setText("");
        TXTcupo.setText(" ");

    }//GEN-LAST:event_BTNnuevoActionPerformed

    private void BTNborrarcteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNborrarcteActionPerformed
        // TODO add your handling code here:
        int borrar = tbl_Datos_Clientes.getSelectedRowCount();
        if(borrar>0){
            md.removeRow(borrar-1);
            JOptionPane.showMessageDialog(null, "dato borrado satisfactoriamente");
        } else{
            JOptionPane.showMessageDialog(null, "no hay datos");
        }

    }//GEN-LAST:event_BTNborrarcteActionPerformed

    private void BTNborrarallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNborrarallActionPerformed
        // TODO add your handling code here:

        int borrartodo= tbl_Datos_Clientes.getRowCount();
        for(int i=borrartodo-1;i>-1;i--){
            md.removeRow(i);
            JOptionPane.showMessageDialog(null, "se borro todo los datos");

        }

    }//GEN-LAST:event_BTNborrarallActionPerformed

    private void BTNbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNbuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BTNbuscarActionPerformed

    private void CBB_ocupacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBB_ocupacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBB_ocupacionActionPerformed

    private void btnmodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodificarActionPerformed
        // TODO add your handling code here:
        int modificar = tbl_Datos_Clientes.getSelectedRow();

        if(modificar>-1){
            String[] dato={TXTnombre.getText(),TXTapellido.getText(),TXTedad.getText(),TXTcedula.getText(),TXTcupo.getText(), CBB_ocupacion.getSelectedItem().toString()};

            md.insertRow(modificar, dato);
            md.removeRow(modificar+1);
            JOptionPane.showMessageDialog(null, "dato modificado satisfactoriamente");
        } else{
            JOptionPane.showMessageDialog(null, "no hay datos para modificar");
        }

    }//GEN-LAST:event_btnmodificarActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        JF_tienda Cliente=new JF_tienda();

        try{

            Cliente =new  JF_tienda();

        }
        catch(Exception ex)
        {
            Logger.getLogger(JF_tienda.class.getName()).log(Level.SEVERE,null,ex);
        }
        Cliente.setLocationRelativeTo(null);
        Cliente.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:

        JF_producto_tienda articu=new JF_producto_tienda();

        try{

            articu=new JF_producto_tienda();

        }
        catch(Exception ex)
        {
            Logger.getLogger(JF_producto_tienda.class.getName()).log(Level.SEVERE,null,ex);
        }
        articu.setLocationRelativeTo(null);
        articu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        conexion lista=new conexion();
        JOptionPane.showMessageDialog(null,lista.listaArticulo());
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:

        JF_Facturacion_Tienda Fact=new JF_Facturacion_Tienda();

        try{

            Fact =new  JF_Facturacion_Tienda();

        }
        catch(Exception ex)
        {
            Logger.getLogger(JF_Facturacion_Tienda.class.getName()).log(Level.SEVERE,null,ex);
        }
        Fact.setLocationRelativeTo(null);
        Fact.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        try {
            // TODO add your handling code here:
            JF_acerca_de_tienda acerca=new JF_acerca_de_tienda();
            
            try{
                
                acerca =new JF_acerca_de_tienda();
                
            }
            catch(IOException ex)
            {
                Logger.getLogger(JF_acerca_de_tienda.class.getName()).log(Level.SEVERE,null,ex);
            }
            acerca.setLocationRelativeTo(null);
            acerca.setVisible(true);
            this.setVisible(false);
        } catch (IOException ex) {
            Logger.getLogger(JF_tienda.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:

        JF_Version Version=new JF_Version();

        try{

            Version=new JF_Version();

        }
        catch(Exception ex)
        {
            Logger.getLogger(JF_Version.class.getName()).log(Level.SEVERE,null,ex);
        }
        Version.setLocationRelativeTo(null);
        Version.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // TODO add your handling code here:

        System.exit(0);
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        conexion lista=new conexion();
        JOptionPane.showMessageDialog(null,lista.listaClientes());
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        conexion lista=new conexion();
        JOptionPane.showMessageDialog(null,lista.listaFactura());
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JF_tienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JF_tienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JF_tienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JF_tienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JF_tienda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNborrarall;
    private javax.swing.JButton BTNborrarcte;
    private javax.swing.JButton BTNbuscar;
    private javax.swing.JButton BTNguardar;
    private javax.swing.JButton BTNnuevo;
    private javax.swing.JButton BTNsalir;
    private javax.swing.JComboBox CBB_ocupacion;
    private javax.swing.JMenu Jacerca;
    private javax.swing.JMenu Jarticulos;
    private javax.swing.JMenu Jcliente;
    private javax.swing.JMenu Jfacturacion;
    private javax.swing.JTextField TXTapellido;
    private javax.swing.JTextField TXTcedula;
    private javax.swing.JTextField TXTcupo;
    private javax.swing.JTextField TXTedad;
    private javax.swing.JTextField TXTnombre;
    private javax.swing.JButton btnmodificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbl_Datos_Clientes;
    // End of variables declaration//GEN-END:variables
}
